CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  rol VARCHAR(100) NOT NULL,
  activo BOOLEAN DEFAULT TRUE,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE estados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  activo BOOLEAN DEFAULT TRUE
) ENGINE=InnoDB;

CREATE TABLE franquicias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  ubicacion VARCHAR(100) NOT NULL,
  activo BOOLEAN DEFAULT TRUE
) ENGINE=InnoDB;

CREATE TABLE reclamaciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT NOT NULL,
  descripcion TEXT NOT NULL,
  tipo VARCHAR(100) NOT NULL DEFAULT "Servicio",
  estado_id INT DEFAULT 1 NOT NULL,
  franquicia_id INT NOT NULL,
  activo BOOLEAN DEFAULT TRUE,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (usuario_id)    REFERENCES usuarios(id),
  FOREIGN KEY (estado_id)     REFERENCES estados(id),
  FOREIGN KEY (franquicia_id) REFERENCES franquicias(id)
) ENGINE=InnoDB;